### ISSUE TITLE
Add instructions to setup development environment in README.md

### ISSUE THREAD

**Issue by Rishabhraghwendra18** [Rishabhraghwendra18/hackmoreish#7]
In the `Getting Started` section add these steps:
- 1st step:  fork 
- 2nd setp clone the repo
```
git clone github.com/<your-username>/hackmoreish
```
- 3rd step: 
```
cd hackmoreish
```
- 4th step: Install dependencies
```
npm install
```

**Comment by Anubha13kumari** [comment]
I want to work on tnis issue.Can you assign this to me?

**Comment by Rishabhraghwendra18** [comment]
Ok.. @Anubha13kumari go ahead
