### ISSUE TITLE
Change vertical scroll bar style 

### ISSUE THREAD

**Issue by Rishabhraghwendra18** [Rishabhraghwendra18/hackmoreish#9]
Change vertical scroll bar from : 
![Screenshot from 2021-12-16 17-32-37](https://user-images.githubusercontent.com/43534227/146369170-7f66a15a-c1db-4d1a-a955-ce2f0746b436.png)

**To this:**
![Screenshot from 2021-12-16 17-37-42](https://user-images.githubusercontent.com/43534227/146369282-4f6433fc-9b84-4572-868f-eaf0e64feefd.png)

**Comment by nitin094-hub** [comment]
![Screenshot (29)](https://user-images.githubusercontent.com/73329655/146379863-86b85928-f468-44c7-8673-5d2c3980b823.png)

Can you explain why this error is coming up?

**Comment by Rishabhraghwendra18** [comment]
@nitin094-hub > ![Screenshot (29)](https://user-images.githubusercontent.com/73329655/146379863-86b85928-f468-44c7-8673-5d2c3980b823.png)
> 
> Can you explain why this error is coming up?

It's because of some environment variables are not set up . Hence nothing is getting passed to `content` variable . You can comment out the theme tag in `pages/index.js` file .

**Comment by Rishabhraghwendra18** [comment]
@nitin094-hub are you working on this issue ?

**Comment by nitin094-hub** [comment]
yeah!
what happend?

**Comment by nitin094-hub** [comment]
Can you assign me this issue?

**Comment by Rishabhraghwendra18** [comment]
Nice PR @nitin094-hub . Thanks . If you want to work on other issues or found a bug feel free to comment or open an issue for it.
